apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: selfhealtestapp
  namespace: argocd
spec:
  destination:
    namespace: argocdappdemo
    server: 'https://kubernetes.default.svc'
  source:
    path: 0-Demo_Files/Nginx_Deployment
    repoURL: 'https://github.com/glayneon/ArgoCD-Complete-Master-Course.git'
    targetRevision: HEAD
  project: defaults
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
